### ISSUE TITLE
Describe the relationship with Yggdrasil

### ISSUE THREAD

**Issue by zimbatm** [threefoldtech/mycelium#119]
Knowing where projects come from helps understand the lineage and also captures some of the learnings that happened in the process. It's also helpful to the user as they are now able to make a more informed decision on their technology choices.

Do you remember what brought you to re-implement Yggdrasil. Were there particular design decisions or technology choices that didn't work for you? I looked in this repo and couldn't find a rationale document.

**Comment by delandtj** [comment]
While Yggdrasil seemed like the warm water reinvented for overlay networks, their claims for a planetary scale network based on a DHT averred to show the same strains as IPFS, even with only a few thousand nodes. So latency spikes, lots of topology chatter, and overall inconsistent bandwidth.
That was not without reasons :
  - nodes in the topology were not aware of available bandwidth
  - the topology itself (or the structure) doesn't lend itself to be able to become locality-aware.
  - empirical evidence suggested that in terms of bandwidth with more that 2 hops data transfers were slower than most '90ies modems. So the network was basically only usable for very small messages, ssh, and for the rest we needed to revert to other more direct communications through our own wireguard-based mesh network.  
  - latency spikes notwithstanding, we also had to cope with unreliable connectivity, which is inherent to publicly driven and operated networks. 
All these reasons are quite understandable considering the design decisions, maturity of the project (it even stalled for basically a whole year because of the main developer's busy agenda), and the way the network is run, with volunteers for whom network bandwidth is not free nor abundant (mostly). 
  - some research was done to work with the existing code, but appeared early on a path that we shouldn't take.

Zerotier suffers from other problems, mainly because of the (then) limited infrastructure to carry the network forward. Adding  moons to try to get the network a bit more performant led to no noticeable difference and the network  always felt off, sluggish and also unreliable. The financial situation of the company getting stretched out at that time led us to forego zerotier as main driver for our overlay. NIH? nah ;-)

Also, as things evolved, there were requirements for the grid to convey secure messages between nodes for which any existing library could be used. 
As the idea ripened to start research in using the babel protocol as a building block for an overlay network (master's thesis  for an intern), the protocol lends itself naturally as a message-passing hub too, making mycelium a more generalized tool for the grid itself, instead of 'just' a network.

The main advantage of a self-developed overlay network is the fact that the feature set is fully owned. The more, as the routing protocol is loosely based on Babel, it can be extended/ameliorated driven by progressive insight and requirements.

The main takeaway from this implementation is the simplicity, and being written in Rust, it's **very** performant (a lot of care has been taken in that part). 

For a project of +- 10K LoC till now for an MVP, it's a breeze and an overall good decision.

More to come on new features, but first: scale it up and up and up to see where we start seeing strain on as well chatter as routing tables.

**Comment by zimbatm** [comment]
Thanks a lot for taking the time to write this overview.

I haven't tried Yggdrasil but share the same experience with ZeroTier. One of the most frustrating aspects is how opaque the connectivity, and lack thereof is. And it always takes a minute or two to establish the routes. Comparatively, mycelium is very much instant in my little lab setup.

Is it correct to assume that privacy isn't a goal of the protocol? If a user joins the network with their laptop, tracking them by their public IP would be pretty straightforward.

**Comment by delandtj** [comment]
Indeed, it's an open network. But keep in mind that the communication between 2 instances still is private. 

we have an FR open to be able to use the same binary but make it a private network based on shared keys for if you would want to connect multiple nodes privately. 

Still ironing out the kinks in the implementation details, but then you have a fully private network.

**Comment by LeeSmet** [comment]
I'll consider this answered, feel free to reopen if there are further questions.
