### ISSUE TITLE
the docs for the binary file is not clear

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#123]
threefoldtech/tfgrid-sdk-ts#2186 
### Description 
through the testing mycelium this part of the docs is not clear
![Screenshot 2024-02-15 at 6 08 23 PM](https://github.com/threefoldtech/mycelium/assets/110984055/961a2a21-8231-4f7b-b3fa-24a7d9a057fa)
i think user should do both download the binary and install mycelium
and it should be clear that user should move the binary to
`usr/local/bin`

![Screenshot 2024-02-15 at 9 44 53 AM](https://github.com/threefoldtech/mycelium/assets/110984055/6f8adf92-14a4-4c1d-b508-9b1f6771e0bd)
also there is another issue that the binary of linux contains `unknown ` in it's name

**Comment by LeeSmet** [comment]
> i think user should do both download the binary and install mycelium
and it should be clear that user should move the binary to
`usr/local/bin`

Could you please elaborate on why that is required?

> also there is another issue that the binary of linux contains unknown in it's name

This is correct  `{x86_64/aarch64}-unknown-linux-musl`  is the full, generally accepted, target triplet

**Comment by khaledyoussef24** [comment]
> Could you please elaborate on why that is required?
> 
> > to put the file in the binary so user can user mycelium commands easily 
`mycelium inspect --json
``sudo mycelium --peers tcp://83.231.240.31:9651 quic://185.206.122.71:9651 --tun-name utun9
`

**Comment by LeeSmet** [comment]
While it can be considered convenient, there is really no need to do this to simply run the binary. Additionally, doing this would be an "installation", and it's up to the user to choose whether he wants that or not. Finally, what actually needs to happen to have access as `mycelium` instead of `./mycelium` (or whatever the path to the binary is from the PWD), is that the binary is moved to (a directory in) the PATH variable. Perhaps the user added the Downloads directory on there, in which case none of that is needed (though it would be a highly unusual setup).

All of this considered, it's up to the users to choose if they want to or not, and its up to them to decide what to put where on their system.
