### ISSUE TITLE
mycelium is not working on mac

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#125]
after downloading the binary of mycelium version [v0.3.2](https://github.com/threefoldtech/mycelium/releases/tag/v0.3.2) for macos
i can not connect 
<img width="1666" alt="Screenshot 2024-02-20 at 12 06 00 PM" src="https://github.com/threefoldtech/mycelium/assets/110984055/060c1904-40d2-47ff-9a8e-fe4175fb56b9">

steps made 
download the repo as mentioned in the docs and downloaded and ran the latest binary for [mycelium-x86_64-apple-darwin.tar.gz](https://github.com/threefoldtech/mycelium/releases/download/v0.3.2/mycelium-x86_64-apple-darwin.tar.gz)

**Comment by khaledyoussef24** [comment]
tried the same steps on linux using the linux binary and worked well

**Comment by LeeSmet** [comment]
In order to properly know what is going on I'd need to have the full log output, as well as the debug info (which is printed after sending a SIGUSR1 to the process) for both the linux and mac process. Also, considering there is no route to send the multicast beacon, what is the native IPv6 situation like?

**Comment by khaledyoussef24** [comment]
verified it worked fine with the new binary and i was able to connect to my machines
