### ISSUE TITLE
peer_manager: periodically refresh interfaces

### ISSUE THREAD

**Issue by flokli** [threefoldtech/mycelium#136]
It seems `local_discovery` only runs once, on startup.

There should be something running periodically, so new interfaces get included in local discovery shortly after they appear.

Example: plugging into a monitor / docking station that has its own LAN port.

**Comment by LeeSmet** [comment]
The local discovery itself actually sends a beacon every minute, but the listening interfaces are indeed only registered once. The link local discovery isn't really optimal right now, and it's being improved in between other things. I've also noticed windows doesn't really like the current implementation, so that will also need some investigation.

**Comment by flokli** [comment]
Nice! It looks like this fixed local node discovery in my setup. Thanks!

**Comment by flokli** [comment]
Can you craft a release with this too?

**Comment by LeeSmet** [comment]
I'll probably do that on friday
