### ISSUE TITLE
Internal Peer discovery 

### ISSUE THREAD

**Issue by Mic92** [threefoldtech/mycelium#138]
Once I joined the VPN, how can I discover other machines in the VPN without having to know their public key up-front? Is there a way to have some sort of DNS, so I don't have to copy and paste IP addresses?

**Comment by flokli** [comment]
You can ask the API for the list of peers, and assuming local discovery works you should see them. You still need to figure out who is who, so best would be to exchange pubkeys out of band.

**Comment by LeeSmet** [comment]
Since every node gets a /64 subnet, the network only exchanges routes to these /64s. Just from the routing info alone, you can't really tell IP's of other nodes. Since the IP is derived from the public key, that default IP is set on the TUN interface on startup and public keys are also exchanged (together with the routing), it is technically possible to derive the default IP's of the other nodes in the API. Of course, this is not a guarantee, as a user might choose to change the IP on the TUN interface after it is started, and a node can host multiple IP's (which might not be on the same machine if the node acts as a router on the local network).

As for DNS, since these are all valid IPv6 addresses, you _could_ set up DNS AAAA records for services you wish to expose on the network.

As a side note, there have been some internal background talks about implementing some kind of "self announcement" in the network, which would allow some simple autodiscovery, but nothing concrete in that regard as it stands.

**Comment by LeeSmet** [comment]
It's an idea which popped up at some point. One of the main questions will be if there is a noticeable benefit to implementing it in the network layer, instead of reusing existing functionality on top. And indeed, spamming traffic would be a large problem imo. Right now, we are relying on existing functionality like DNS, which should work out of the box and is proven technology.

**Comment by LeeSmet** [comment]
I'll close this for now, feel free to reopen if there are further questions on this subject
