### ISSUE TITLE
v0.5.1 does not work, but v0.4.0 does on my local machine

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/mycelium#216]
# Situation

I tried mycelium with the latest current release and it didn't work. I tried with the v0.4.0 version (the one on the manual currently), and it worked perfectly.

# Procedure

Followed the guide on the manual: https://manual.grid.tf/documentation/system_administrators/mycelium/installation.html

**Comment by LeeSmet** [comment]
I am going to assume that you are trying to connect to a deployment on the grid. The problem here is that after v0.5.0 was released, instead of updating _all_ public nodes, I decided to only update half and leave the other half on v0.4 for some time to allow a somewhat smooth transition. It seems this was a mistake is it removes the urgency of updating.

The reason the old version works, is because of these not yet updated public peers, which creates a full path of v0.4.x nodes to zos. This will stop working as soon as the remaining public notes are updated. Bascically, between v0.4.x and v0.5.x you can only reach the target if there is a fully connected path of nodes on the same version.
