### ISSUE TITLE
Mycelium binary crashes 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#261]
Mycelium binary crashes whenever I try to start it on both linux and macos
![Screenshot 2024-05-21 at 5 00 51 PM](https://github.com/threefoldtech/mycelium/assets/110984055/5b80edb3-1376-4fb1-a3ad-2319c9663288)
![telegram-cloud-photo-size-4-5938336523957157694-y](https://github.com/threefoldtech/mycelium/assets/110984055/a5e0f7ca-f84f-4f14-87b3-7ca324f087de)

**Comment by LeeSmet** [comment]
As explained in https://github.com/threefoldtech/mycelium/issues/242#issuecomment-2101092469 and https://github.com/threefoldtech/mycelium/issues/110#issue-2091071121, this error means a similarly named device is already present. Since network device names need to be unique, you can use the `--tun-name` flag to provide a unique name for the interface.
