### ISSUE TITLE
Error protocol not available with v0.5.2

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/mycelium#274]
If I try running v0.5.1 it works. With v0.5.2 I get this error and mycelium does not start:

```
May 29 15:45:32  mycelium[79448]: Error: Os { code: 92, kind: Uncategorized, message: "Protocol not available" }
```

Some searches suggest that this could have to do with unsupported socket options. I'm on Linux.

**Comment by LeeSmet** [comment]
How are you starting mycelium?

Additionally, are there any other relevant logs available?

**Comment by scottyeager** [comment]
It's the same result whether I start with systemd or manually. There's a total of two log lines. The first is the normal one that prints the public key, and then the error.

**Comment by LeeSmet** [comment]
This is probably related to the setup of the quic socket given the single log line before the error, and the fact that the process exits. Though between 0.5.1 and 0.5.2 nothing changed there, so that's a bit strange. At this point the best bet would be to run strace to try and figure out which syscall is actually failing

**Comment by scottyeager** [comment]
I figured out my issue with some help from strace. It turns out I accidentally downloaded the aarch64 binary and my system was executing it without warning using qemu due to my `binfmt_misc` config. At least I can report that this particular use case is not supported.

Thanks for the tip, @LeeSmet.
