### ISSUE TITLE
to be able to run mycelium next to yggdrasil please find an alternative ipv6 subnet

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/mycelium#33]

**Comment by scottyeager** [comment]
So here's the reference on available choices: https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml

Yggdrasil uses `200::/7` because, as they say, it's a "deprecated" range. In this context deprecated means that a range was previously assigned for a certain purpose and it has since been unassigned. While it's possible that use of a deprecated range is safer than use of a never assigned range (this isn't clear to me), it's not absolutely safe, because such ranges are still reserved and could be reassigned in the future.

Our options broadly are:

1. Another deprecated range (`fec0::/10`, for example)
2. A reserved range that hasn't yet been assigned (`0800::/5`, `a000::/3`, etc)
3. Unique Local Unicast (`fc00::/7`)
4. Some other [special purpose](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) range (such as ORCHIDv2)

Some considerations:

1. Chance of future conflicts with routable addresses at the IP link layer (and on what timeline—even filling `2000::/3` doesn't seem a concern at this point)
2. In the case of using a shared range, such as the ULA range, the chance of conflicts with other uses of that range
3. Distinguishability from regular IPv6 addresses (the Yggdrasil range is nice in this respect, as the addresses are obviously Yggdrasil addresses)
4. How much space do we need? (since our addresses are hashes of public keys, this is a question of the chance of collisions at a given level of network participation—more bits means more possible hashes)

Among the possibilities, I think that the [ORCHIDv2](https://www.rfc-editor.org/rfc/rfc7343.html) range is particularly interesting. From the RFC:

> These identifiers are intended to be globally unique in a statistical sense, non-routable at the IP layer, and routable at some overlay layer.

This matches the needs for `mycelium` addresses well. ORCHIDv2 addresses take the range `2001:20::/28`, so they are not easily distinguished from regular IPv6 addresses and conforming to the ORCHID spec might not make sense for us. On the other hand, it's potentially a way to fit into the IPv6 space in a sanctioned way rather than just laying a rogue claim to some unassigned space.

**Comment by delandtj** [comment]
the purpose of mycelium is to replace ygg, and have the the exact same thing when it's about an overly network.
I have been looking around to find another range, but I gather that it then defies the purpose.
We can have a discussion about that. Maybe we should, maybe we shouldn't. Either way, the design itself was specifically tailored for __replacing__ ygg.

**Comment by scottyeager** [comment]
Even if we decide to drop Yggdrasil on the Grid, people might still want to run both networks on their machines. I think we'd do better to take a cooperative approach that makes interoperation possible.

We should also remember that Mycelium is not a 1-1 replacement for Yggdrasil until it runs on both MacOS and Windows. Whether or not we support both simultaneously on the Grid for some period of time is a discussion to have in the other issue on the Zos repo, but I'm not convinced that we can just cut it over one day, especially since we won't know how Mycelium works at scale until we try it and deploying new versions of software into Zos is a slow process.

**Comment by xmonader** [comment]
This won't be feasible in 3.13, moved to 3.14 until that's settled

**Comment by scottyeager** [comment]
Discussed this with @despiegk, and we agree that it's better to choose a different subnet so Mycelium can interoperate with Yggdrasil. Even if we don't want to run both simultaneously within Zos, it should be possible for those who want to and also possible to bridge between the two

**Comment by LeeSmet** [comment]
35c6a7501305dddad3056b23b582b909e99b947f
