### ISSUE TITLE
Preshared key for encrypting control messages, so that a user can create a private network for his own machines

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/mycelium#86]
no need for Tailscale any more :-D
Things will just work 
Eat this bradfitz

**Comment by LeeSmet** [comment]
The main problem here is that we don't have an actual handshake, so the nodes will connect and you could potentially receive traffic. Though it should just be discarded upon being received as the routing table will stay empty. Other than that it should be fine. Additionally, features in different connection protocols might improve this by being able to embed this in the configuration, which would be a more ideal scenario.

**Comment by LeeSmet** [comment]
So it would seem that TLS actually has an ideal solution already. TLS supports ciphersuites which use a PSK instead of certificates (see https://datatracker.ietf.org/doc/html/rfc4279). The main problem is that rustls currently does not support this. There is some openssl code for this, but that would mean going down to openssl. Still it might be a good idea to quickly check that out now, and marking this feature as experimental (i.e. no API compatibility) or something

**Comment by LeeSmet** [comment]
As it turns out, TLS1.3 no longer uses specialized cipher suites, but instead relieas on built in PSK functionality. Still need to figure out how to best access that.

**Comment by LeeSmet** [comment]
The rust openssl crate does no support the new specific tls1.3 callbacks to properly set the key for the connection. As a result, SHA384 digests don't work (only SHA256 does with these callbacks). Going further on this, `TLS_AES_256_GCM_SHA384` won't work, though `TLS_AES_128_GCM_SHA256` and `TLS_CHACHA20_POLY1305_SHA256` _will_ work.
